### ISSUE TITLE
DO NOT CHANGE THIS REPO

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/isotc211-glossary#12]
This repo is undergoing irreversible changes -- DONT CHANGE THIS REPO UNTIL THIS TICKET IS CLOSED. Thanks.

**Comment by skalee** [comment]
Can I keep my own temporary branch for a while? It will be discarded later.

**Comment by ronaldtse** [comment]
The migration has occurred and the repo can be changed again. Thanks!
