### ISSUE TITLE
`authoritativeSources` in localizedConcepts YAML are empty objects

### ISSUE THREAD

**Issue by ribose-jeffreylau** [geolexica/isotc211-glossary#27]
This causes Paneron to not be able to render sources for concept definitions, for all languages.

<details>
<summary>click for screenshot</summary>

<img width="153" alt="Screenshot 2023-04-24 at 7 08 56 PM" src="https://user-images.githubusercontent.com/2649467/233979501-8bbaa32b-0382-45b0-81d5-1f9fc260a776.png">

</details>

**Comment by strogonoff** [comment]
It should be `authoritativeSource`.

**Comment by ribose-jeffreylau** [comment]
Yes, but still empty... :(

**Comment by stefanomunarini** [comment]
@ribose-jeffreylau where should this data be coming from? I can fix this if someone knows where to get it.

**Comment by ribose-jeffreylau** [comment]
Thanks @stefanomunarini for looking into it.  Yes, it's still relevant, given the following (current latest) configuration:

- Paneron: https://github.com/paneron/paneron/commit/3678dad8a744a51e9f936139a467319c7f849f27
- paneron-extension-glossarist: https://github.com/glossarist/paneron-extension-glossarist/commit/a0c299e858bafaba88c9b00addbb05375312b7d5 (v2.0.17)
- glossary: https://github.com/geolexica/isotc211-glossary/commit/339481717cd81d2d1b32d060cef80049956d2b56

## Possibly relevant lines

- https://github.com/paneron/glossarist-registry-conversion-tools/blob/master/convert.py#L135-L138

It seems that the convert tool needs to look for things like `data['data'].get('sources')` and filter for `type == 'authoritative'`:

https://github.com/geolexica/isotc211-glossary/blob/main/concepts/concept-10.yaml#L17-L25

## Target shape

If the convert tool can produce something like the following, then I believe Paneron should be able to read it:

- https://github.com/MetaverseStandards/metaversestandards-glossary/blob/e9779c9d797c8fbdb2c78001a63f94f8f68fde49/msfglossary/localized-concept/20be593a-4d53-4b83-aa14-3ac167e1aeec.yaml#L13-L15

## Relevant issues / Background reading

- https://github.com/geolexica/jekyll-geolexica/issues/14
- https://github.com/geolexica/jekyll-geolexica/issues/12
- https://github.com/geolexica/isotc211-glossary/issues/6
- https://github.com/glossarist/glossarist-ruby/pull/75

**Comment by stefanomunarini** [comment]
Hi @ribose-jeffreylau thanks for the well detailed task description. 

Fixed in https://github.com/geolexica/isotc211-glossary/commit/417866cd6e1212cafc5fa25ebd825f0d6a13ad3b 

However, even though the link appears formatted as a URL, it is not clickable or copiable. Not sure if this is supposed to be as such?
<img width="1512" alt="Screenshot 2024-02-06 at 14 07 48" src="https://github.com/geolexica/isotc211-glossary/assets/4653319/9a3bd958-3acc-42f0-bcea-c6fc4f5128e4">

Moreover, I think another piece of data is missing here. Notice the "For other languages, see:" . What is Paneron expecting there?

**Comment by ribose-jeffreylau** [comment]
@stefanomunarini For the clickability of links, I think @strogonoff will have a better idea.

As for the `Not found: 7` error, I think it is indeed an error.  It should point to this record (`UUID: 7f61690f-6e2b-51c2-9ac4-ffa0bc8f17ce`):

<img width="912" alt="Screenshot 2024-02-07 at 19 17 35" src="https://github.com/geolexica/isotc211-glossary/assets/2649467/7da6805d-727a-400f-8c03-3f4bb45f4cdb">

For the record, this error is present in all the language-specific descriptions for this particular concept.  Not sure if it got corrupted during import or some other reasons.

**Comment by stefanomunarini** [comment]
> As for the `Not found: 7` error, I think it is indeed an error. It should point to this record (`UUID: 7f61690f-6e2b-51c2-9ac4-ffa0bc8f17ce`):

Can you be more specific on how a localised-concept (e.g. https://github.com/geolexica/isotc211-glossary/blob/main/geolexica/localized-concept/0002e0ac-f74e-5ae0-9b58-f459c7d60cfa.yaml) data structure should be updated to include this property?

**Comment by ribose-jeffreylau** [comment]
I think there is nothing wrong with the data structure, but rather, there may be some edge cases not accounted for in the glossarist extension: https://github.com/glossarist/paneron-extension-glossarist/blob/master/src/classes/localizedConcept/util.ts#L13-L44 ...  cc: @strogonoff

**Comment by stefanomunarini** [comment]
Shouldn't localized-concept data include a reference to the "parent"?

**Comment by ribose-jeffreylau** [comment]
Continuing this issue here: #46 .

**Comment by ribose-jeffreylau** [comment]
[As mentioned](https://github.com/geolexica/isotc211-glossary/issues/27#issuecomment-1929856006), fixed in https://github.com/geolexica/isotc211-glossary/commit/417866cd6e1212cafc5fa25ebd825f0d6a13ad3b.  Closing.

Thanks @stefanomunarini !
