### ISSUE TITLE
Citation of clause numbers incorrectly encoded in some cases

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/isotc211-glossary#28]
https://github.com/geolexica/isotc211-glossary/blob/bd03730de0587aaf2909486bd3548765860d9b79/concepts/concept-1000.yaml#L21

Here, the "(E), " should not exist. The "(E)" technically belongs to the PubID, which means "the English version".

"E" is not part of the clause number.

This task is to clean up these instances.

**Comment by stefanomunarini** [comment]
@ronaldtse please see linked PR #29
