### ISSUE TITLE
(URGENT) update language codes in data set as per latest tc211-termbase gem

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/isotc211-glossary#48]
@HassanAkbar can you please help update the language codes in the output data set using the newly released gem? Thanks.

Latest version is 0.2.7.

_Originally posted by @ronaldtse in https://github.com/geolexica/isotc211.geolexica.org/issues/210#issuecomment-2074357799_

**Comment by HassanAkbar** [comment]
@ronaldtse updated the glossary to use correct codes here -> https://github.com/geolexica/isotc211-glossary/pull/47

**Comment by ronaldtse** [comment]
Closed in #47.
