### ISSUE TITLE
Remove the deprecated `concepts/` directory?

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/isotc211-glossary#51]
Now we have the `geolexica/` directory, is the `concepts/` directory already deprecated?

Can we delete `concepts/` ?

**Comment by HassanAkbar** [comment]
@ronaldtse Yes, we can delete the `concepts/` directory, it is not being used for site generation anymore.

**Comment by strogonoff** [comment]
That’s great, I was wondering the same.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau since you're working on this repository, can you help delete the `concepts/` directory? Thanks.
