### ISSUE TITLE
Turn off scheduled workflow that deploys Paneron Web from the main branch?

### ISSUE THREAD

**Issue by strogonoff** [geolexica/isotc211-glossary#56]
Currently, deploying with Paneron Web (the site-builder package) from main branch results in broken site due to broken links between localized concept descriptions & universal/generalized concepts. Staging branch works, however.

Unless we decisively update the main branch so that concept links make sense, we should turn off the scheduled workflow, I think.

The math in the main branch won’t work, but that’s smaller beans and we should be able to fix it shortly.

**Comment by ribose-jeffreylau** [comment]
Should be fixed in https://github.com/geolexica/isotc211-glossary/commit/d4721d6ef4c1d3aacc6b79916784a6d185eb7039.
